---
fixtures:
  repositories:
    augeasproviders_core: https://github.com/simp/augeasproviders_core.git
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub.git
    mount_core: https://github.com/simp/pupmod-puppetlabs-mount_core.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
  symlinks:
    ima: "#{source_dir}"
